<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-12 18:48
=======
# Generated by Django 4.2 on 2023-05-02 15:25
>>>>>>> 7c46afe8e19fddf1c5d717d94f9e66669aca341f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
    ]
